# Generated by Django 3.0.8 on 2022-06-13 16:04

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deal',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('totalRating', models.IntegerField(default=3)),
                ('degree', models.IntegerField(default=3)),
            ],
        ),
    ]
